theme: jekyll-theme-cayman
title: Falconism - Ultra minimalist blog engine optimized for cheap VPS
description: Ultra-minimalist blogging platform. Tiny memory footprint. Built-in SEO tools. Embedded database. Embedded webserver. Packed in ONE tiny executable fi
